### ISSUE TITLE
bad line in install instructions

### ISSUE THREAD

**Issue by morkeltry** [macintoshhelper/learn-sql#11]
`sudo -u psql -c "ALTER USER $PSQL_MY_USERNAME WITH SUPERUSER"`

should be:

`sudo -u postgres psql -c "ALTER USER $PSQL_MY_USERNAME WITH SUPERUSER"`

:sunglasses:

**Comment by macintoshhelper** [comment]
I addressed the issue in this PR: https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

Does this solve the issue?

**Comment by sbinlondon** [comment]
@morkeltry @macintoshhelper Can we close this issue now that it has been addressed?
