### ISSUE TITLE
problems had with FACN2

### ISSUE THREAD

**Issue by ZooeyMiller** [macintoshhelper/learn-sql#12]
(these are written in note form so that there is a record of them, will write up properly later, all students who required this were on linux, 1 mint which was fixed with the first way then 2 ubuntu fixed with the latter)

problems:

if `you have held broken packages` or something similar try running:

`sudo apt-get -yf install postgresql postgresql-contrib`

the `-f` flag gets apt-get to try to fix any package problems whilst installing.

## if "cannot resolve hostname"

`hostname`

(this will log your hostname)

`sudo nano /etc/hostname`

make sure the contents of /etc/hostname is the same as what is returned by `hostname`

then run `sudo nano /etc/hosts`, you'll get something that looks like this:

```
127.0.0.1       localhost
127.0.1.1       [YOUR-HOSTNAME-HERE]

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

what is in the place of `[YOUR-HOSTNAME-HERE]` should be the same as what is returned by running `hostname` and the contents of your `/etc/hostname` file, if it is not currently, change it so that it is.

when you run something like `sudo apt-get update` you should no longer get `unable to resolve hostname`

## if when trying to install/update stuff you now get 503 errors or something along the lines of `unable to contact [A UBUNTU SERVER HERE]`

Then there may be some problems with contacting that host, for me, I tried pinging each server and the ping worked, but still couldn't resolve the host whilst trying to run `apt-get update` or istalling postgres

then went into system settings, software and updates, and changed "download from" to main, and it worked with

`sudo apt-get -yf install postgresql postgresql-contrib`

**Comment by eliasmalik** [comment]
@ZooeyMiller and I had some of these problems for FACG2 as well

**Comment by sbinlondon** [comment]
@eliascodes @ZooeyMiller Has this issue been resolved? Can we close it?

**Comment by eliasmalik** [comment]
This can probably be closed with the creation of a "troubleshooting" section/document. I expect people will continue having similar problems, but the main guide shouldn't be bloated with edge cases.

**Comment by ZooeyMiller** [comment]
Agree with @eliascodes. If these issues cause real hassle again then we can always add it to the docs somewhere.
