### ISSUE TITLE
Add link to postgres.app

### ISSUE THREAD

**Issue by azayneeva** [macintoshhelper/learn-sql#15]
It's worth adding instructions to download the [postgres.app](https://postgresapp.com/) for people on MAC struggling with installing postgresql.

Though installing postgresql via CLI should their first port of call.

**Comment by macintoshhelper** [comment]
Thanks for the suggestion. Does #16 address this issue? If so, I'll merge the PR and auto-close this issue.

**Comment by azayneeva** [comment]
Yes, thanks a lot!
