### ISSUE TITLE
No mention of how to exit the psql command line interface.

### ISSUE THREAD

**Issue by Roger-Heathcote** [macintoshhelper/learn-sql#17]
setup.md mentions how to get into the psql command line interface but doesn't mention how to exit it...

\q
\quit

**Comment by macintoshhelper** [comment]
Thanks for the feedback, does PR #18 make it clear enough how to exit `psql`? `ctrl` + `D` is a standard for exiting pretty much any Terminal process (other than `vim`).

**Comment by macintoshhelper** [comment]
(PR auto closed this issue) Just want to check that this is resolved and no need to re-open 🙂.
