### ISSUE TITLE
make clearer separation between regular setup instructions & addition of "pgcli"

### ISSUE THREAD

**Issue by jsms90** [macintoshhelper/learn-sql#5]
Because of the order of instructions, students are typing `brew install pgcli` once they're inside psql

> Then to login to the database, use `psql mydb`.
>
>To setup autocomplete for PostgreSQL, you can install pgcli with brew:
> ```
> brew install pgcli
> ```

+ [ ] Make a clearer distinction between the two sections:
  + main installation instructions for MAC
  + optional extra section to add `pgcli`

+ [ ] Add _really_ obvious statement about what pgcli is
    > Pgcli is a command line interface for Postgres with auto-completion and syntax highlighting.

**Comment by macintoshhelper** [comment]
I've moved it into a separate bonus section and added a statement that `pgcli` is an alternative postgres CLI client, and added Linux instructions as requested in #9 .

Does this PR solve the issue?
https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

**Comment by sbinlondon** [comment]
@jsms90 @macintoshhelper This issue appears to have been solved - can we close this?
