### ISSUE TITLE
Make Mac installation instructions clearer in setup.md

### ISSUE THREAD

**Issue by rachaelcodes** [macintoshhelper/learn-sql#6]
A couple of us made the mistake of typing `psql mydb` rather than `psql <type your username here>`. Perhaps this (and the similar pgcli) command could be made clearer.

**Comment by jsms90** [comment]
@rachaelcodes Thanks for raising!! This is a great suggestion.

One little thing - the title of this issue could be a bit clearer. Every issue raised about `setup.md` could probably have this title. Think about it from the perspective of looking through a list of issues and needing the titles to be distinct from each other :+1: 

@macintoshhelper Are you happy to make this change in a PR and tag @rachaelcodes as a reviewer?

**Comment by macintoshhelper** [comment]
I made things too complicated with the `read`, etc. I've moved creating databases into a separate section and removed the `read` stuff and improved comments.

Does this PR solve the issue?
https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

**Comment by sbinlondon** [comment]
@rachaelcodes @jsms90 @macintoshhelper This issue appears to have been solved - can we close this?
