### ISSUE TITLE
add contents "mac installation" & "linux installation"

### ISSUE THREAD

**Issue by jsms90** [macintoshhelper/learn-sql#7]
MAC users are just going through the whole file, not realising that they should only be doing the top half.

+ [ ] Add contents at the top which links to the headings below

1. MAC installation
2. Linux installation

+ [ ] Maybe also add something at the bottom of the MAC installation section, explicitly saying that they can stop.

**Comment by macintoshhelper** [comment]
Thanks for your suggestions, I've separated the sections better, and moved some parts out of installation to minimise confusion.

Does this PR solve the issue?
https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

**Comment by sbinlondon** [comment]
@jsms90 @macintoshhelper This issue appears to have been solved - can we close this?
