### ISSUE TITLE
Following it line by line caused problems !

### ISSUE THREAD

**Issue by y-zaky** [macintoshhelper/learn-sql#8]
![screen shot 2017-07-31 at 11 08 11](https://user-images.githubusercontent.com/25886395/28773249-abc0a676-75e0-11e7-9d9c-17a61d9c6f3e.png)

Perhaps make it clear that you can copy and paste the entire object into bash for installation?

**Comment by jsms90** [comment]
@bowssy88 Is the problem here that you copy pasted `PSQL_MY_USERNAME=$(whoami)`?

**Comment by absorpheus** [comment]
We think it would have been easier to run the instructions line by line (rather than copying and pasting the entire object), but we would need more explanation of what each line is doing.

For example: The command read, and echo were not clear in particular.

**Comment by macintoshhelper** [comment]
I made it a bit too complicated, I've separated creating databases into a separate section and removed `read`. 

Does this PR solve the issue?
https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

**Comment by macintoshhelper** [comment]
I've removed the brackets since it's better to run the commands separately to understand/remember that they do. You can still copy/paste the entire thing.

**Comment by morkeltry** [comment]
Since this is meant to be a new language for us, using brackets which are not meant to be entered, such as `CREATE DATABASE <database name here>;` is a bit confusing. It's no biggie, but maybe something clearly not meant to be entered, such as `CREATE DATABASE //database name here//;` would be clearer?

**Comment by sbinlondon** [comment]
@morkeltry @macintoshhelper @y-zaky @AbdullahChaudhry Has this issue been resolved to everyone's satisfaction? Can we close it?
