### ISSUE TITLE
PGCLI installing instructions for Linux missing

### ISSUE THREAD

**Issue by polyccon** [macintoshhelper/learn-sql#9]
You can use the link [pgcli](https://www.pgcli.com/install) for instructions.
```//Checks if you have pip installed - the following is for Debian (ubuntu, mint) -check website for other
$ which pip

//install pip
$ sudo apt-get install python-pip

//Install libpq python dependency
$ sudo apt-get install libpq-dev python-dev 

//Install pgcli
//$ sudo pip install pgcli```

**Comment by macintoshhelper** [comment]
I moved the instructions into a separate bonus section and added Linux (Debian) instructions.

Does this PR solve the issue?
https://github.com/macintoshhelper/learn-sql/blob/postgresql/setup/refactor/postgresql/setup.md

**Comment by polyccon** [comment]
Yes looks good to me :-) Maybe also mention that it's for Debian systems as well ;-)

**Comment by macintoshhelper** [comment]
I've added Redhat and Debian instructions and specified what distro they are.

**Comment by polyccon** [comment]
Cool then I can close the issue! Thanks :+1:
